<a href="https://colab.research.google.com/github/GuidoAH/Optimization-Algorithms/blob/main/Algoritmos_Optimizacion_Actividad_Final_Guido_A_Heienbrok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Algoritmos de Optimización - Actividad Final**
#**Nombre:** Guido Alexander | **Apellido:** Heienbrok
#Link GitHub: https://github.com/GuidoAH/Optimization-Algorithms

**Problema**<br>
Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada jornada que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por jornada. El objetivo es planificar las sesiones por jornada de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible. <br>
Link a los datos: https://bit.ly/36D8IuK

**Nota:** Los códigos están escritos en inglés por costumbre.

# INDICE - Preguntas contestadas
1. (*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?

2. ¿Cuántas posibilidades hay teniendo en cuenta todas las restricciones?

3. (*) ¿Cuál es la estructura de datos que mejor se adapta al problema? Argumenta la respuesta. (Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumenta)

4. (*)¿Cuál es la función objetivo?

5. (*)¿Es un problema de maximización o minimización?

6. Diseña un algoritmo para resolver el problema por fuerza bruta

7. Calcula la complejidad del algoritmo por fuerza bruta

8. (*)Diseña un algoritmo que mejore la complejidad del algoritmo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

9. (*)Calcula la complejidad del algoritmo

10. Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorio.
* Conclusones
* Referencias

**1. (*) ¿Cuantas posibilidades hay sin tener en cuenta las restricciones?**

Sin tener en cuenta las restricciones hay $n!$ posibilidades. Es decir, hay $30! = 2.652528598 \times 10^{32}$ combinaciones de tomas posibles.

**2. ¿Cuántas posibilidades hay teniendo en cuenta todas las restricciones?**

Teniendo en cuenta únicamente el caso del número máximo de tomas por jornada, es decir, 6 tomas por día y por lo tanto un total de 5 jornadas/sesiones, las posibilidades de dividir 30 tomas en 5 grupos de 6 tomas son:
$\frac{30!}{(6!)^5} \cdot \frac{1}{5!} \approx 10^{19}$ combinaciones.

Si tuvieramos en cuenta que se pueden grabar menos de 6 tomas por jornada, habría que considerar un número mucho mayor de combinaciones.

**3. ¿Cuál es la estructura de datos que mejor se adapta al problema? Argumenta la respuesta (Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumenta)**

La estructura de datos que mejor se adapta es una lista de listas.
La lista principal representa las sesiones/días de grabación y cada elemento de esa lista es un sublista que contiene las tomas que se graban en esa jornada/sesión en concreto.

Por ejemplo:<br>
Solución = [[día 1], [día 2],  [día 3], etc...]<br>

y a su vez cada día/sesión está estructurado como:<br>
día 1 = [toma 15, toma 3, toma 22]<br>
día 2 = [toma 27, toma 1, toma 19]<br>
día 3 = [toma 12, toma 14, toma 7]<br>
etc...

**4. ¿Cuál es la función objetivo?**

La función objetivo es el gasto debido a los actores de doblaje para una distribución de sesiones de grabación dada.

**5. ¿Es un problema de maximización o minimización?**

Es un problema de minimización. Se pretende minimizar el gasto dedicado a actores de doblaje durante el rodamiento de una película.


**6. Diseña un algoritmo para resolver el problema por fuerza bruta**

In [ ]:
# Importar librerías
import random
import numpy as np
import copy
import datetime
from itertools import permutations

In [ ]:
# Introducir datos del problema

# Reparto de las tomas y actores
data = [[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]]

# Algoritmo por fuerza bruta
Por simplificar el algoritmo se ha calculado el algoritmo de fuerza bruta como sigue:

1. Generar una lista que contenga todas las permutaciones posibles de las 30 tomas.
2. Por simplificar, cada permutación se dividirá en 5, quedando grupos de 5 con 6 días cada una. Esto representerá 5 días/sesiones de grabación con 6 tomas en cada jornada/sesión.
3. Para cada solución se calcula el gasto.
4. Se elige aquella distribución de tomas que menor gasto genere.

- **Desventaja:** Se contabilizarán muchas soluciones que sean iguales cambiando únicamente el orden de los días. Dado que el orden de los días no importa, únicamente las sesiones por día, habrá muchos cálculos innecesarios. De hecho, las combinaciones son tantas que el código por 'fuerza bruta' no puede hacer 'run'.

- **Ventaja:** El algoritmo por permutaciones es más fácil de implementar que uno de combinatoria, donde se calcule todas las posibilidades de distribuir las 30 tomas entre un mínimo de 5-30 días/sesiones. Siendo 5 el número mínimo de sesiones posibles y 30 el número máximo posible de sesiones (1 toma por día).

In [ ]:
# Definir función de coste
# Para una solución dada busca el número de actores total que han participado en una jornada
def calculate_cost(data, solution):
  solution = [list(item) for item in solution]
  data = np.array(data)
  total_cost = 0
  for day in solution: # Recorrer jornada a jornada para una misma solución y contar actores
      actors = np.any(data[day], axis=0)
      total_actors = np.sum(actors)
      total_cost += total_actors
  return total_cost

def generate_all_combinations(takes):
  # Generar números del 1 al número máximo de tomas
  numbers = list(range(takes))

  # Generar todas las permutaciones posibles
  all_permutations = list(permutations(numbers))

  return all_permutations

# Dividimos la permutación obtenida en 5 jornadas de 6 tomas
def split_list_into_sublists(lst, num_sublists):
    avg = len(lst) // num_sublists
    remainder = len(lst) % num_sublists

    sublists = []
    start = 0
    for i in range(num_sublists):
        end = start + avg + (1 if i < remainder else 0)
        sublists.append(lst[start:end])
        start = end

    return sublists

# Aplicar la división por jornadas a todas las permutaciones
def generate_all_solutions(lst, num_sublists):
  all_solutions = []
  for item in lst:
    all_solutions.append(split_list_into_sublists(item, num_sublists))
  return all_solutions

# Recorrer todas las soluciones y elegir la de menor coste.
def best_combination(all_solutions):
  best_cost = float('inf')
  best_schedule = []
  for solution in all_solutions:
    cost = calculate_cost(data, solution)
    if cost < best_cost:
      best_cost = cost
      best_schedule = solution

  return best_schedule, best_cost

# Definir algoritmo principal de fuerza bruta
def brute_force(data, number_of_takes, sublists):
 all_permutations = generate_all_combinations(number_of_takes)
 all_solutions =  generate_all_solutions(all_permutations, sublists)
 best_schedule, best_cost = best_combination(all_solutions)

 return ("La mejor solución es: ", best_schedule, "El coste es: ", best_cost)

# Definir parámetros y ejecutar algoritmo de fuerza bruta
number_of_takes = 30
number_of_takes_per_day = 6
min_number_of_days = number_of_takes/number_of_takes_per_day
brute_force(data, number_of_takes, min_number_of_days)

**7. Calcula la complejidad del algoritmo por fuerza bruta**

Debido a las permutaciones (todas las combinaciones posibles de tomas), el algoritmo de tiene una complejidad de $O(n!)$.

**8. (*)Diseña un algoritmo que mejore la complejidad del algoritmo por fuerza bruta.
Argumenta porque crees que mejora el algoritmo por fuerza bruta.**

A continuación se elabora una algoritmo **GRASP** para encontrar las mejores soluciones. El algoritmo esta construido como sigue:

1. Se genera una lista de tomas posibles
2. A continuación se elige una toma al azar (**R**andom).
3. Para la toma elegida en el paso 2 se crea una lista de actores que participan en la toma.
4. Para la lista de actores del paso 3 se calculan todas las todas las tomas que los actores tengan en común. Se elige aquella toma que más actores en común como siguiente toma. Aquí es donde entra en juego la voracidad del algoritmo (**G**reedy), dado que se busca hacer coincidir en un misma jornada/sesión al máximo número de actores con el máximo número de tomas en común.
5. Se repiten los pasos 3-5.
6. Una vez encontrada una solución, se realiza una búsqueda local intercambiando las tomas entre las jornadas/sesiones programadas para una solución dada (**A**daptative).
7. Se crea un bucle **multiarranque** para explorar un espacio de soluciones.
8. Para las soluciones del paso 7 se calcula el gasto y se elige aquella distribución de tomas por jornada/sesión que menor gasto dedicado a los actores de doblaje conlleve.

# Algoritmo GRASP

**Funciones auxiliares**

In [ ]:
# Crear lista de tomas disponibles
def create_available_takes(data):
  return list(range(len(data)))

# Elegir toma al azar
def choose_random_take(available_takes):
  return random.choice(available_takes)

# Eliminar toma de las tomas elegidas
def remove_chosen_take(available_takes, chosen_take):
  return available_takes.remove(chosen_take)

# Crear lista de actores que participan en la toma
def create_actor_list(data, chosen_take, actor_list=None):
  # Si la lista está vacía
  if actor_list == None:
    actor_list = []
    for actor_index, has_participated in enumerate(data[chosen_take]):
        if has_participated == 1:
            actor_list.append(actor_index)
  else:
    # Añadir actores a lista ya existente
    for actor_index, has_participated in enumerate(data[chosen_take]):
        if has_participated == 1:
            actor_list.append(actor_index)
            actor_list = list(set(actor_list))
  return actor_list

# Crear lista de actores que participan en la toma elegida
def next_best_take(data, available_takes, actor_list):
  best_take = None
  most_common_actors = 0

  for take in available_takes: # Buscar actores con más tomas en común para elegir siguiente toma
      common_actors = sum(1 for actor_index in actor_list if data[take][actor_index] == 1)
      if common_actors > most_common_actors:
          most_common_actors = common_actors
          best_take = take

  return best_take

def calculate_cost(data, solution):
  data = np.array(data)
  total_cost = 0
  for day in solution: # Calcular cuantos actores en total participan en una jornada de grabación
      actors = np.any(data[day], axis=0)
      total_actors = np.sum(actors)
      total_cost += total_actors
  return total_cost

# Definir intercambios para búsqueda local
def swap_takes_between_days(solution, data):
  best_cost = calculate_cost(data, solution)
  best_solution = solution.copy()

  for day1_index, day1 in enumerate(solution):
      for day2_index, day2 in enumerate(solution):
          if day1_index != day2_index:
              for take1_index, take1 in enumerate(day1):
                  for take2_index, take2 in enumerate(day2):
                      # Intentar intercambiar las tomas entre jornadas diferentes
                      solution_copy = copy.deepcopy(solution)
                      solution_copy[day1_index][take1_index] = take2
                      solution_copy[day2_index][take2_index] = take1

                      new_cost = calculate_cost(data, solution_copy)

                      if new_cost < best_cost:
                          best_cost = new_cost
                          best_solution = solution_copy

  solution.clear()
  solution.extend(best_solution)

  return solution

# Definir búsqueda local
def local_search(solution, data, max_iterations=100):
  current_iteration = 0
  while current_iteration < max_iterations:
      swap_takes_between_days(solution, data)
      current_iteration += 1

  return solution  # Devolvemos la programación de doblaje optimizada


def represent_solution(solution, cost):
  schedule = solution
  cost = cost

  for i in range(len(schedule)):
    print(f"Reparto de tomas día {i+1}: ", schedule[i])

  print("El coste total es de: ", cost)

**Algoritmo principal**

In [ ]:
def schedule_sessions(data):
  available_takes = create_available_takes(data)
  solution = []

  while available_takes:
    # Eligir una toma al azar.
    chosen_take = choose_random_take(available_takes)

    # Eliminar la toma elegida de la lista de tomas disponibles.
    remove_chosen_take(available_takes, chosen_take)

    # Crear una lista de actores que participan en la toma elegida.
    actor_list = create_actor_list(data, chosen_take)

    # Eligir aquella toma de la lista de tomas disponibles con más actores en común
    best_take = next_best_take(data, available_takes, actor_list)

    # Agregar las tomas seleccionadas al programa de doblaje
    day = [chosen_take]

    # Agregar tomas hasta completar un máximo de 6 tomas por día
    while len(day) < 6 and best_take is not None:
        day.append(best_take)
        remove_chosen_take(available_takes, best_take)

        actor_list = create_actor_list(data, best_take, actor_list)
        best_take = next_best_take(data, available_takes, actor_list)

    # Añadir día a solución final
    solution.append(day)

    # Aplicar búsqueda local
    solution = local_search(solution, data)

  #Calcular el coste
  cost = calculate_cost(data, solution)

  return solution

**multiarranque (multi start)**

In [ ]:
# Emplear un multiarranque (multi start)
def GRASP(data, num_iterations):
    best_solution = None
    best_cost = float('inf')

    for _ in range(num_iterations):
        solution = schedule_sessions(data)
        total_cost = calculate_cost(data, solution)

        if total_cost < best_cost:
            best_cost = total_cost
            best_solution = solution

    return(represent_solution(best_solution, best_cost))

# Resultados

In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 1
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [8, 0, 5, 6, 19, 11]
Reparto de tomas día 2:  [28, 7, 9, 25, 20, 10]
Reparto de tomas día 3:  [29, 12, 1, 21, 16, 2]
Reparto de tomas día 4:  [14, 3, 4, 27, 15, 24]
Reparto de tomas día 5:  [13, 17, 23, 18, 22]
Reparto de tomas día 6:  [26]
El coste total es de:  30
Tiempo de ejecución transcurrido: 0:00:37.506538


In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 10
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [28, 0, 5, 6, 7, 11]
Reparto de tomas día 2:  [9, 10, 3, 14, 2, 25]
Reparto de tomas día 3:  [26, 8, 21, 19, 1, 12]
Reparto de tomas día 4:  [17, 13, 16, 18, 22, 23]
Reparto de tomas día 5:  [24, 4, 15, 20, 27, 29]
El coste total es de:  28
Tiempo de ejecución transcurrido: 0:04:23.499420


In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 20
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [25, 0, 5, 6, 9, 11]
Reparto de tomas día 2:  [28, 7, 10, 2, 3, 14]
Reparto de tomas día 3:  [1, 19, 12, 21, 8, 26]
Reparto de tomas día 4:  [23, 13, 16, 17, 18, 22]
Reparto de tomas día 5:  [24, 4, 15, 20, 27, 29]
El coste total es de:  28
Tiempo de ejecución transcurrido: 0:08:03.351960


In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 30
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [20, 28, 7, 9, 10, 25]
Reparto de tomas día 2:  [0, 11, 21, 1, 6, 19]
Reparto de tomas día 3:  [14, 2, 8, 12, 26, 5]
Reparto de tomas día 4:  [13, 16, 17, 18, 22, 23]
Reparto de tomas día 5:  [29, 27, 4, 15, 24, 3]
El coste total es de:  27
Tiempo de ejecución transcurrido: 0:13:32.298556


In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 40
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [4, 0, 5, 10, 12, 19]
Reparto de tomas día 2:  [20, 3, 7, 28, 14, 2]
Reparto de tomas día 3:  [9, 11, 1, 25, 21, 8]
Reparto de tomas día 4:  [13, 16, 18, 22, 17, 23]
Reparto de tomas día 5:  [27, 24, 6, 15, 29, 26]
El coste total es de:  27
Tiempo de ejecución transcurrido: 0:17:58.658887


In [ ]:
# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Generar solución
iterations = 50
GRASP(data,iterations)

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

Reparto de tomas día 1:  [21, 0, 4, 6, 10, 1]
Reparto de tomas día 2:  [11, 19, 12, 25, 8, 9]
Reparto de tomas día 3:  [20, 3, 7, 14, 2, 28]
Reparto de tomas día 4:  [23, 13, 16, 17, 18, 22]
Reparto de tomas día 5:  [24, 5, 15, 27, 29, 26]
El coste total es de:  27
Tiempo de ejecución transcurrido: 0:22:27.466481


**9. (*)Calcula la complejidad del algoritmo** <br>
La complejidad del algoritmo empleado mejora solo ligeramente.
Debido a los bucles internos de cada funcion auxiliar y la llamada de las funciones auxiliares a la función principal la complejidad del algoritmo es aproximadamente:<br>

Complejidad = $n\cdot n\cdot m\cdot m\cdot d\cdot d\cdot t\cdot t$
Donde n son tomas totales, m actores, d días, t tomas por día. Eligiendo el caso de mayor complejidad daría por tanto:<br>

**Complejidad $\approx O(a^{n})$ -> Orden exponencial.**

**10. Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorio.**

In [ ]:
# Crear instancia 2
# 20 tomas, 10 actores, 1 iteracion
rows = 20
columns = 10
data1 = np.random.randint(2, size=(rows, columns))
print(data2)
print('\n')

# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Aplicar algoritmo GRASP
iterations = 1
GRASP(data2,iterations)
print('\n')

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

[[1 1 1 0 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 1 1 1 1 0 0]
 [1 0 1 1 1 0 0 1 1 0]
 [0 0 0 1 0 1 1 1 0 1]
 [0 0 1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 0 1 0 1]
 [1 0 1 1 1 0 0 1 0 0]
 [0 1 0 1 0 0 1 1 1 0]
 [0 0 1 1 0 0 1 1 1 0]
 [1 0 1 1 1 1 0 1 0 0]
 [1 1 0 1 0 0 1 1 0 1]
 [1 1 0 0 1 0 0 0 1 1]
 [1 1 0 1 1 0 1 0 1 1]
 [1 0 0 0 0 0 0 1 1 1]
 [1 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 1]
 [0 1 1 1 1 0 1 0 0 1]
 [1 1 0 0 0 1 1 0 1 0]
 [0 0 1 1 1 1 0 0 0 1]]


Reparto de tomas día 1:  [3, 7, 10, 2, 9, 5]
Reparto de tomas día 2:  [19, 15, 17, 0, 11, 4]
Reparto de tomas día 3:  [13, 12, 18, 16, 6, 8]
Reparto de tomas día 4:  [1, 14]
El coste total es de:  31


Tiempo de ejecución transcurrido: 0:00:05.024925


In [ ]:
# Crear instancia 3
# 30 tomas, 10 actores, 1 iteracion
rows = 30
columns = 10
data3 = np.random.randint(2, size=(rows, columns))
print(data3)
print('\n')

# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Aplicar algoritmo GRASP
iterations = 1
GRASP(data3,iterations)
print('\n')

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

[[0 1 0 0 1 1 1 0 1 0]
 [0 1 1 1 1 0 0 1 1 1]
 [0 0 0 1 1 0 1 0 1 0]
 [1 0 0 0 1 1 1 0 1 0]
 [0 1 1 0 0 0 0 1 0 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 0 0 1 0 1 0 1 0 1]
 [1 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 1 0 1 1 1 0]
 [1 1 1 1 0 0 0 1 0 0]
 [1 0 1 1 1 0 1 1 0 1]
 [1 1 0 0 1 1 0 1 1 0]
 [1 1 0 1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 1 0 1 1]
 [1 1 0 1 1 1 1 1 1 1]
 [1 0 0 1 0 0 1 1 1 1]
 [1 0 1 1 1 0 1 0 1 0]
 [0 0 1 1 1 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 1]
 [1 1 1 1 1 0 0 1 0 1]
 [0 0 1 1 0 0 1 1 1 1]
 [0 0 0 1 0 1 1 1 0 0]
 [1 0 1 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 0 1 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 0]
 [0 1 0 1 0 0 0 0 1 0]
 [1 0 1 0 0 1 0 1 0 1]]


Reparto de tomas día 1:  [5, 15, 1, 22, 20, 8]
Reparto de tomas día 2:  [10, 18, 16, 21, 14, 17]
Reparto de tomas día 3:  [28, 0, 2, 3, 7, 11]
Reparto de tomas día 4:  [9, 13, 12, 29, 26, 6]
Reparto de tomas día 5:  [25, 19, 27, 23, 24, 4]
El coste total es de:  41


Tiempo de ejecución transcurrido: 0:00:

In [ ]:
# Crear instancia 4
# 50 tomas, 10 actores, 1 iteracion
rows = 50
columns = 10
data4 = np.random.randint(2, size=(rows, columns))
print(data4)
print('\n')

# Contar tiempo de ejecución
start_time = datetime.datetime.now()

# Aplicar algoritmo GRASP
iterations = 1
GRASP(data4,iterations)
print('\n')

# Terminar de contar el tiempo de ejecución
end_time = datetime.datetime.now()
elapsed_time = end_time - start_time
print("Tiempo de ejecución transcurrido: {}".format(elapsed_time))

[[1 0 1 1 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 1 1 0]
 [1 0 1 0 0 0 0 1 1 1]
 [0 1 1 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 1 1 0 1]
 [0 1 0 1 0 1 0 0 0 1]
 [0 0 1 1 0 1 1 1 0 1]
 [1 1 1 0 1 1 1 0 1 0]
 [1 1 0 1 0 0 0 1 0 1]
 [0 1 0 0 1 1 1 1 0 1]
 [1 0 0 1 1 1 0 0 1 1]
 [0 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 1 1 0 1 0 0]
 [1 0 0 0 1 1 1 0 1 1]
 [0 0 1 0 1 1 1 0 1 0]
 [0 1 1 1 1 0 0 1 1 0]
 [1 0 0 1 1 1 0 0 0 0]
 [0 1 0 1 0 1 1 0 0 1]
 [0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 1 0 0 0 0 1 0]
 [1 1 1 0 1 1 0 1 0 1]
 [1 0 0 0 1 1 0 1 0 0]
 [1 1 1 1 0 1 1 1 0 1]
 [1 0 0 0 0 1 1 1 0 1]
 [0 1 1 1 1 1 1 0 1 0]
 [1 1 1 0 0 0 1 1 0 0]
 [0 1 0 1 0 0 1 1 1 0]
 [1 1 1 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 1 1]
 [1 0 1 1 0 0 0 0 1 1]
 [1 1 0 0 0 1 1 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 1 1 0 1 1 1 0 0 0]
 [1 1 0 1 0 1 0 1 0 1]
 [0 1 0 0 1 1 0 1 1 0]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 1]
 [1 1 0 1 0 0 1 1 0 0]
 [1 1 0 1 0 0 0 0 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 0 0 1 1]
 [1 0 1 0 0

# Conclusiones
Algoritmo GRASP:<br>
Iteraciones = 1;  Tomas n = 30 -> Coste 30 -> Tiempo = 37s <br>
Iteraciones = 10; Tomas n = 30 -> Coste 28 -> Tiempo = 4min 23s <br>
Iteraciones = 20; Tomas n = 30 -> Coste 28 -> Tiempo = 08min 03s <br>
Iteraciones = 30; Tomas n = 30 -> Coste 27 -> Tiempo = 13min 32s <br>
Iteraciones = 40; Tomas n = 30 -> Coste 27 -> Tiempo = 17min 58s <br>
Iteraciones = 50; Tomas n = 30 -> Coste 27 -> Tiempo = 22min 27s <br>

El algoritmo GRASP se  estanca a partir de las 30 iteraciones. El algoritmo encuentra el valor 27 como el coste más bajo.
El tiempo promedio de ejecución crece lineal al aumentar el número de iteraciones $i$ y mantener fijo el número de tomas $n$.

Sin embargo al aumentar el número $n$ de tomas, el tiempo promedio de ejecución crece exponencialmente para un número fijo de iteraciones $i$:

Iteraciones = 1; Tomas n = 20 -> Tiempo = 5s <br>
Iteraciones = 1;Tomas n = 30 -> Tiempo = 14s <br>
Iteraciones = 1; Tomas n = 50 -> Tiempo = 3m 27s

# Referencias
[1] - Apuntes de clase<br>
[2] - https://blog.myrank.co.in/permutations-and-combinations-division-of-objects-into-groups/ <br>
[3] - https://math.stackexchange.com/questions/2450837/how-many-combinations-of-groups-are-there-possible-in-a-set-of-50-students-with